### PR TITLE
Hardened the NumberComparator to have better support for number types.

### PR DESCRIPTION
**Pull request by kaspersorensen**
(Sorry for the code reformatting, but the old was clearly wrong - used
tabs instead of spaces)

### CODE REVIEW

**Comment by LosD** [comment]
Ugh, huge reformatting. But fair, most of the file was changed anyway, and it had the wrong indentation character before (and the secret 'add ?w=1 to URL' Github trick saved the comparison).

**Comment by LosD** [comment]
I realize we are for much more than SQL, but the null comparisons being equal worries me a bit, "NULL is never equal to anything" is  a pretty important part of SQL (and maybe one of the few things all SQL vendors can agree on).

OTOH, NULL is never NOT equal to anything else, so this may still be wrong SQL-wise.

**Comment by LosD** [comment]
Okay, it probably doesn't matter. It doesn't seem to be used for (SQL) equals unless there's a need to parse it anyway.

**Comment by LosD** [comment]
Let's go with the LGTM :)

**Comment by kaspersorensen** [comment]
Glad that you sorted it out ;-)

**Comment by LosD** [comment]
Yeah. That @losd guy started panicking, but I calmed him down :)

**Pull request closed without merging**
