### PR TITLE
Fix excel decimal formatter

### PR DESCRIPTION
**Pull request by b789**
Fix to solve the problem of having the decimal values from excel truncated to two digits.

https://issues.apache.org/jira/browse/METAMODEL-190

### CODE REVIEW

**Comment by kaspersorensen** [comment]
Hmm Travis build failed, but it seems to be some issue on the build server ...
Did you run the full build after your change? I could imagine that changing this in the FormatHelper could also have effects in other places than the Excel module.

**Comment by b789** [comment]
Launching mvn compile in my local fork master compile fine and 4.0.x fails with: Failed to execute goal org.apache.rat:apache-rat-plugin:0.8:check (rat-verify) on project MetaModel: Too many unapproved licenses.
After the change the situation still the same.
Sorry if i made something wrong but i'm not used to this kind of things.

**Comment by kaspersorensen** [comment]
no need to worry about 4.0.x branch :)

I'll do the build myself also tomorrow. If everything is fine, +1 from me and I'll merge unless anyone else objects.

**Comment by kaspersorensen** [comment]
hmm something's odd here. You PR is suggesting we add this to the 4.0.x branch while it should probably do it on the master branch.

If I add the patch to my master branch then my build fails with the following issue:

```
Failed tests:
  FormatHelperTest.testNumberFormat:32 expected:<987643.21[]> but was:<987643.21[3456343]>

Tests run: 281, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] MetaModel .......................................... SUCCESS [  4.185 s]
[INFO] MetaModel core API ................................. FAILURE [ 13.168 s]
[INFO] MetaModel module for collection and POJO-based DataContexts. SKIPPED
[INFO] MetaModel module for fixed width value files ....... SKIPPED
[INFO] MetaModel module for Excel spreadsheets ............ SKIPPED
[INFO] MetaModel module for comma-separated value (CSV) files SKIPPED
[INFO] MetaModel module for JSON files .................... SKIPPED
[INFO] MetaModel module for XML files ..................... SKIPPED
[INFO] MetaModel module for relational JDBC databases ..... SKIPPED
[INFO] MetaModel module for Elasticsearch analytics engine  SKIPPED
[INFO] MetaModel module for Apache Hadoop, HDFS, YARN integration SKIPPED
[INFO] MetaModel module for Apache HBase .................. SKIPPED
[INFO] MetaModel module for Apache Cassandra database ..... SKIPPED
[INFO] MetaModel module for MongoDB databases ............. SKIPPED
[INFO] MetaModel module for CouchDB databases ............. SKIPPED
[INFO] MetaModel module for OpenOffice.org database files . SKIPPED
[INFO] MetaModel module for Salesforce.com ................ SKIPPED
[INFO] MetaModel module for SugarCRM ...................... SKIPPED
[INFO] MetaModel full package, including DataContext factories SKIPPED
[INFO] MetaModel module for Spring enabled configuration .. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

**Comment by b789** [comment]
You're right i messed up a bit, i'll close this pull request and open another one on the master branch.

**Pull request closed without merging**
