### PR TITLE
METAMODEL-218: Fixed

### PR DESCRIPTION
**Pull request by kaspersorensen**
This fixes METAMODEL-218 by adding a few return statement in DefaultQueryRewriter.

Also updated the test template to ensure that it's working on all the databases covered by these tests.

### CODE REVIEW

**Comment by drexler42** [comment]
I'll give it a go and provide feedback

**Comment by kaspersorensen** [comment]
Did you come to any conclusion @drexler42 ?

**Comment by drexler42** [comment]
Not yet, I'm afraid. Having trouble building a DataCleaner with this MM in it.

**Comment by drexler42** [comment]
I can copy the customers table directly into Postgres now. The fix works. A word of warning though:
- MetaModel 4.4.2-SNAPSHOT is not compatible with DataCleaner master.
-- Package names of ElasticSearch datastore is changed in MM, and must be changed accordingly in DC.
-- The new MM neo4j module introduces a tattletale clash on an json library.

I excluded the culprit from DC, but then the API module does not compile anymore. I gave up on solving that at that point.
```
			<dependency>
				<groupId>org.apache.metamodel</groupId>
				<artifactId>MetaModel-full</artifactId>
				<exclusions>
					<exclusion>
						<artifactId>json</artifactId>
						<groupId>org.apache.geronimo.bundles</groupId>
					</exclusion>
				</exclusions>
			</dependency>
```

The fix in itself is fine. So I'll merge it.

**Comment by kaspersorensen** [comment]
I merged in master ... Was just a conflict in CHANGES.md. But let's see that Travis builds correctly before we merge to master

**Comment by drexler42** [comment]
Let's merge then!

**Pull request closed without merging**
