### PR TITLE
RESTful API swagger docs

### PR DESCRIPTION
**Pull request by kaspersorensen**
This is a continuation of #110 which adds a Swagger definition file for the REST endpoints. I'd like a review of the swagger.yaml file contents please.

(For ease-of-reading I would recommend pasting it in to e.g. http://editor.swagger.io/)

### CODE REVIEW

**Comment by LosD** [comment]
Aw man. Same branch.

**Comment by kaspersorensen** [comment]
No but it has the other branch as it's parent

**Comment by kaspersorensen** [comment]
But commit 0a82d13b19ea0f8aa3aabcd140caaf3274a8e5b4 is the only substantial piece so far.

**Comment by kaspersorensen** [comment]
I'm merging this into the `feature/5.x/rest-api` branch

**Comment by kaspersorensen** [comment]
No wait, on second though I have a remark myself ... I don't like that this PR bundles all of swagger-ui into the source code tree. It would be much better to just download swagger ui as part of the build.

**Comment by kaspersorensen** [comment]
Closing this and #110 in order to create a new PR without all the commit-bound remarks.

**Pull request closed without merging**
