### PR TITLE
METAMODEL-1169 Preserve milliseconds when rewriting query with Date operand (master)

### PR DESCRIPTION
**Pull request by jakubneubauer**

### CODE REVIEW

**Comment by LosD** [comment]
Code LGTM, but this seem like a change that requires an update to the integration tests. However, they might be quite broken, so it might not make much of a difference, but at least we should take a look.

**Comment by jakubneubauer** [comment]
tests were fixed.

**Comment by jakubneubauer** [comment]
To the integration tests:
I found these int. tests related to date/time handling:

- SQLServerJtdsDriverTest.testWorkingWithDates and it is working.
- SQLServerJtdsDriverTest.ignoreTestTimestampValueInsertSelect is now commented out with description that this test was failing and actually somehow wrong

So it looks like it doesn't require any change.

**Comment by LosD** [comment]
Merged

**Pull request closed without merging**
