### PR TITLE
Make the running it tests info more visible and update broken link

### PR DESCRIPTION
**Pull request by ardlema**

### CODE REVIEW

**Comment by kaspersorensen** [comment]
Looks good to me.

**Comment by albertostratio** [comment]
Will you merge this one or do you want me to merge it?

**Comment by kaspersorensen** [comment]
Oh please go ahead, I am not working with the MM codebase at the moment so I don't need the context switch ;-)

**Comment by albertostratio** [comment]
No worries, I will merge this one as well

**Pull request closed without merging**
