### PR TITLE
Added COUNTER data type support. fixes #METAMODEL-149

### PR DESCRIPTION
**Pull request by ardlema**
Added support for COUNTER data type format in Cassandra module.

### CODE REVIEW

**Comment by kaspersorensen** [comment]
The patch looks good to me. But Travis is failing it seems. Can you check it out?

**Comment by LosD** [comment]
Wut? How did you add a new commit without Github realizing it? Amended commit?

(I only know because I was about to add a comment about the missing isConfigured, and you had added it when I submitted :))

- By the way, way to do away with those isConfigured with some kind of mock setup? It's a quite a shame to miss the automated testing for all of CassandraDataContext.

**Comment by albertostratio** [comment]
My bad! Forgot to add the isConfigured() check in the new test that I added.

It's great to have travis-ci!! ;)

**Comment by albertostratio** [comment]
@LosD you are right I ammended my last commit.

We might use an embedded Cassandra server to run the tests: https://github.com/jsevellec/cassandra-unit

**Comment by LosD** [comment]
A biiiit dangerous amending stuff already pushed, if anyone had tried to work from the branch, their branch could easily have been corrupted... But I guess this is so limited in scope that the danger was pretty low. :)

Very good idea with the embedded Cassandra server. It might be a bit too big a change for this PR, but we might want to do it either by itself, or along with other changes later.

**Comment by albertostratio** [comment]
Yes, I ammended the last commit because I knew that I was working on my own in the branch.

Should we create a new jira to address the embedded Cassandra server stuff? I'm willing to make that changes.

**Comment by LosD** [comment]
Hmmm, yeah I guess that would make sense.

**Comment by albertostratio** [comment]
Cool, I'll create it. 

Are you happy to close this PR then?

**Comment by LosD** [comment]
Looks good to me! :-)

**Comment by albertostratio** [comment]
@kaspersorensen are you happy with the patch?

**Comment by albertostratio** [comment]
@LosD I've just created a jira issue: https://issues.apache.org/jira/browse/METAMODEL-154

**Comment by LosD** [comment]
:+1:

**Comment by kaspersorensen** [comment]
Yup!

**Comment by albertostratio** [comment]
Thank you for your comments guys! I'll commit the changes to the apache repo and close the PR.

**Comment by kaspersorensen** [comment]
Oh one little thing ... Could you also update CHANGES.md? :)

**Comment by albertostratio** [comment]
Sure. Already done ;)

**Pull request closed without merging**
