### PR TITLE
Allow empty spaces before AS keyword. Fixes #METAMODEL-138

### PR DESCRIPTION
**Pull request by ardlema**

### CODE REVIEW

**Comment by kaspersorensen** [comment]
Looks good to me.

**Comment by kaspersorensen** [comment]
Feel free to push Alberto :)

**Comment by albertostratio** [comment]
I've just pushed to our "main" repo. Both the PR and the jira issue haven't been closed though (I've included the text "This closes #METAMODEL-138" in the last commit)

**Comment by kaspersorensen** [comment]
You need to close the PR by referring to the PR's ID... So something like "Fixes #22"

**Comment by albertostratio** [comment]
Ups my fault then. Sorry about that! Would you mind closing the PR and the Jira issue? Thank you in advance and sorry again

**Comment by kaspersorensen** [comment]
I cannot close the PR actually, I thought you could :-P

**Comment by kaspersorensen** [comment]
Otherwise make an update to CHANGES.md and put the fixes-part into the commit

**Pull request closed without merging**
