### PR TITLE
More efficiently perform row count operations for HBase.

### PR DESCRIPTION
**Pull request by q977734161**
A filter that will only return the first KV from each row.This filter can be used to more efficiently perform row count operations.

### CODE REVIEW

**Comment by kaspersorensen** [comment]
Please try a rebuild.

Yuck this is getting to often that I say this. We need to get those unstable tests fixed.

**Comment by q977734161** [comment]
ok,I will rebuild.

**Comment by kaspersorensen** [comment]
Hmm @q977734161 I'm trying to fix the build/test issues/instability over in #215. Once it passes, I suggest you merge it in here.

**Comment by kaspersorensen** [comment]
Hi @q977734161 you can pull/merge from my branch now. I believe that should stabilize your build.

**Comment by q977734161** [comment]
I pull/merge from your branch and rebuild,now it's succuess.

**Comment by kaspersorensen** [comment]
LGTM

**Pull request merged**
