### PR TITLE
METAMODEL-1169 Preserve milliseconds when rewriting query with Date operand (4.6)

### PR DESCRIPTION
**Pull request by jakubneubauer**

### CODE REVIEW

**Comment by JoosjeBoon** [comment]
@LosD  - This is a cherry pick of PR 168 intended for the 4.6.x branch. Is it possible to merge it and have a release of that branch this week? Please let me know as we need it for out own release. Thanks!

**Comment by LosD** [comment]
Hmmm... I thought @jakubneubauer had enlisted @kaspersorensen's help for merging this branch to 4.6 and starting the release vote. Any communication that I missed?

**Comment by kaspersorensen** [comment]
I'll merge it in now and start a vote

**Comment by kaspersorensen** [comment]
Hmm for some reason github didn't close this PR, although the change was applied. See commit 449aa70cadbe3cd893683aed55ca6cec2cb33120.

Staging a release for voting now.

**Comment by kaspersorensen** [comment]
Can you please close the PR manually then @jakubneubauer ?

**Comment by LosD** [comment]
I guess the asfgit bot is only watching master.

**Comment by jakubneubauer** [comment]
Ok. Thanks.

**Pull request closed without merging**
