### PR TITLE
METAMODEL-231

### PR DESCRIPTION
**Pull request by tomaszguzialek**
Reproduced METAMODEL-231 with an integration test as well as tested with Neo4j Sandbox (http://neo4j.com/sandbox).

### CODE REVIEW

**Comment by kaspersorensen** [comment]
Cool, thanks Tomasz! :) @ClaudiaPHI maybe you can give it a test run in DataCleaner before we merge it (if you have time)?

**Comment by ClaudiaPHI** [comment]
Yes. I will do it asp. :-)

**Comment by ClaudiaPHI** [comment]
:+1: 
I have tested it and the relationships look nice now. 
image

Movie table: 

image


Person table: 

image

**Comment by kaspersorensen** [comment]
Great, I'll merge it in. Thanks to both of you for fixing and testing :-)

**Pull request closed without merging**
