### PR TITLE
METAMODEL-1128: Size set and enabled scrolling

### PR DESCRIPTION
**Pull request by kaspersorensen**
Here's my stab at a simple fix for METAMODEL-1128.

### CODE REVIEW

**Comment by LosD** [comment]
Code LGTM, but haven't tested.

Should we make a story specifically about looking into using sliced scrolls for performance? I'm not sure how much it'll take, or how big the benefit would be.

**Comment by LosD** [comment]
Tested using DataCleaner. Seems to work fine, and reasonably performant; ~6 seconds to do value distribution on 100K records (value distribution run on two columns)... The test set I used is available here: http://ikeptwalking.com/elasticsearch-sample-data/

One thing I didn't test in depth (since I don't know the dataset) was the correctness of the data retrieved. However, _id keys were unique, so I'm pretty that there's at least no problems with getting same data twice.

**Comment by LosD** [comment]
Should we merge, or wait for reporter of METAMODEL-1128 to give feedback?

**Comment by Juslwk** [comment]
LGTM! I've tested a bit on my own data set, works great!

**Comment by kaspersorensen** [comment]
Great, let's merge it then.

**Pull request closed without merging**
