### PR TITLE
METAMODEL-1215: Removed deprecated code.

### PR DESCRIPTION
**Pull request by kaspersorensen**

### CODE REVIEW

**Comment by LosD** [comment]
Changes themselves LGTM. But shouldn't changes usually be connected to an issue?

**Comment by kaspersorensen** [comment]
Yes let's do that. Then the PR also needs an update to CHANGES.md

**Comment by LosD** [comment]
Oh man. I forgot to check Travis before I merged (and I forgot to do the "closes #224"). I really shouldn't do stuff like this before I had my morning coffee...

Luckily, it seems unrelated (not so luckily, it seems like we still have Excel stability issues...)

**Comment by LosD** [comment]
@kaspersorensen I can't close the issue manually, can you? Otherwise I'll do an empty commit with the magic words

**Comment by kaspersorensen** [comment]
Closed :)

**Pull request closed without merging**
